package com.caseybrooks.androidbibletools.enumeration;

/** Display flags used when printing a Verse object. Provides user with basic
 *  formatting
 */
public enum Flags {
    PRINT_VERSE_NUMBER,         //show numbers with the verse
    PRINT_NEWLINE,              //start each verse on its own new line
    NUMBER_PLAIN,               //16 For God so loved the world...
    NUMBER_PARENTHESIS,         //16) For God so loved the world...
    NUMBER_DOUBLE_PARENTHESIS,  //(16) For God so loved the world...
    NUMBER_DOT,                 //16. For God so loved the world...
    TEXT_NORMAL,                //For God so loved the world...
    TEXT_DASHES,                //___ ___ __ _____ ___ _____...
    TEXT_LETTERS,               //F G S L T W...
    TEXT_DASHED_LETTERS,        //F__ G__ S_ L____ T__ W____...
}
